export const demoMedications = [
  {
    id: 1,
    commonName: 'Sertraline',
    medicalName: 'Sertraline HCl',
    brandGeneric: 'Generic',
    manufacturer: 'Pfizer',
    pharmacy: 'CVS Pharmacy',
    doseAmount: '50mg',
    schedule: 'Daily 8:00am',
    refillSchedule: 'Every 30 days',
    takenToday: true,
    remindersOn: true,
  },
  {
    id: 2,
    commonName: 'Vitamin D',
    medicalName: 'Cholecalciferol',
    brandGeneric: 'Generic',
    manufacturer: 'Nature Made',
    pharmacy: 'Walgreens',
    doseAmount: '2000 IU',
    schedule: 'Daily 9:00am',
    refillSchedule: 'Every 90 days',
    takenToday: false,
    remindersOn: true,
  },
  {
    id: 3,
    commonName: 'Omega-3',
    medicalName: 'Fish Oil EPA/DHA',
    brandGeneric: 'Brand',
    manufacturer: 'Nordic Naturals',
    pharmacy: 'CVS Pharmacy',
    doseAmount: '1000mg',
    schedule: 'Daily 8:00pm',
    refillSchedule: 'Every 60 days',
    takenToday: false,
    remindersOn: false,
  },
  {
    id: 4,
    commonName: 'Atorvastatin',
    medicalName: 'Atorvastatin Calcium',
    brandGeneric: 'Generic',
    manufacturer: 'Teva Pharmaceuticals',
    pharmacy: 'Walgreens',
    doseAmount: '20mg',
    schedule: 'Daily 7:00am',
    refillSchedule: 'Every 30 days',
    takenToday: true,
    remindersOn: true,
  },
  {
    id: 5,
    commonName: 'Lisinopril',
    medicalName: 'Lisinopril',
    brandGeneric: 'Generic',
    manufacturer: 'Sandoz',
    pharmacy: 'CVS Pharmacy',
    doseAmount: '10mg',
    schedule: 'Daily 7:30am',
    refillSchedule: 'Every 30 days',
    takenToday: false,
    remindersOn: true,
  },
];
