export const demoMedications = [
  {
    id: 1,
    commonName: 'Sertraline',
    medicalName: 'Sertraline HCl',
    brandGeneric: 'Generic',
    manufacturers: [{ name: 'Pfizer', percentage: 100 }],
    pharmacy: 'CVS Pharmacy',
    doseAmount: '50mg',
    schedule: 'Daily 8:00am',
    refillSchedule: 'Every 30 days',
    takenToday: true,
    remindersOn: true,
  },
  {
    id: 2,
    commonName: 'Vitamin D',
    medicalName: 'Cholecalciferol',
    brandGeneric: 'Generic',
    manufacturers: [{ name: 'Nature Made', percentage: 100 }],
    pharmacy: 'Walgreens',
    doseAmount: '2000 IU',
    schedule: 'Daily 9:00am',
    refillSchedule: 'Every 90 days',
    takenToday: false,
    remindersOn: true,
  },
  {
    id: 3,
    commonName: 'Omega-3',
    medicalName: 'Fish Oil EPA/DHA',
    brandGeneric: 'Brand',
    manufacturers: [{ name: 'Nordic Naturals', percentage: 100 }],
    pharmacy: 'CVS Pharmacy',
    doseAmount: '1000mg',
    schedule: 'Daily 8:00pm',
    refillSchedule: 'Every 60 days',
    takenToday: false,
    remindersOn: false,
  },
  {
    id: 4,
    commonName: 'Atorvastatin',
    medicalName: 'Atorvastatin Calcium',
    brandGeneric: 'Generic',
    manufacturers: [{ name: 'Teva Pharmaceuticals', percentage: 100 }],
    pharmacy: 'Walgreens',
    doseAmount: '20mg',
    schedule: 'Daily 7:00am',
    refillSchedule: 'Every 30 days',
    takenToday: true,
    remindersOn: true,
  },
  {
    id: 5,
    commonName: 'Lisinopril',
    medicalName: 'Lisinopril',
    brandGeneric: 'Generic',
    manufacturers: [{ name: 'Sandoz', percentage: 100 }],
    pharmacy: 'CVS Pharmacy',
    doseAmount: '10mg',
    schedule: 'Daily 7:30am',
    refillSchedule: 'Every 30 days',
    takenToday: false,
    remindersOn: true,
  },
  {
    id: 6,
    commonName: 'Metformin',
    medicalName: 'Metformin Hydrochloride',
    brandGeneric: 'Generic',
    manufacturers: [
      { name: 'Teva', percentage: 70 },
      { name: 'Sandoz', percentage: 30 },
    ],
    pharmacy: 'CVS Pharmacy',
    doseAmount: '500mg',
    schedule: 'Daily 8:00am',
    refillSchedule: 'Every 90 days',
    takenToday: true,
    remindersOn: true,
  },
  {
    id: 7,
    commonName: 'Levothyroxine',
    medicalName: 'Levothyroxine Sodium',
    brandGeneric: 'Generic',
    manufacturers: [{ name: 'Mylan', percentage: 100 }],
    pharmacy: 'Walgreens',
    doseAmount: '75mcg',
    schedule: 'Daily 6:30am',
    refillSchedule: 'Every 30 days',
    takenToday: true,
    remindersOn: true,
  },
  {
    id: 8,
    commonName: 'Adderall',
    medicalName: 'Amphetamine Salts',
    brandGeneric: 'Brand',
    manufacturers: [
      { name: 'Teva', percentage: 50 },
      { name: 'Sandoz', percentage: 25 },
      { name: 'Aurobindo', percentage: 25 },
    ],
    pharmacy: 'CVS Pharmacy',
    doseAmount: '20mg',
    schedule: 'Daily 7:00am',
    refillSchedule: 'Every 30 days',
    takenToday: false,
    remindersOn: true,
  },
];
