---
name: Release

on:
  push:
    branches:
      - '**' # Watch all branches

jobs:
  release:
    if: github.ref != 'refs/heads/main' # Avoid running on main itself
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GH_TOKEN }}
